### ISSUE TITLE
where is ssdt

### ISSUE THREAD

**Issue by RoJoHub** [toleda/audio_CloverHDMI#12]
```
2. Installs HDMI audio ssdt(s) and edited config.plist
   - Intel/AMD/Nvidia: HDMI audio ssdt (EFI/CLOVER/ACPI/patched/)
```
Where is ssdt？sorry,My english is not good。

The answer if is this？
```

Additional Clover HDMI Audio Installation Methods

ssdt/dsdt/bootloader methods
```

**Comment by toleda** [comment]
EFI/CLOVER/ACPI/patched/

**Comment by RoJoHub** [comment]
@toleda 
There is only one file in the folder.And the file name is `SSDT-SB-OC.aml`
I guess the file is install when i open `MultiBeast`

**Comment by toleda** [comment]
cloverHDMI installs the required HDMI audio ssdt.

**Comment by RoJoHub** [comment]
@toleda.
Also i have another question.
How to  `Set audio_cloverHDMI-xxx.command/gDebug=1`
```
Test Drive
- Set audio_cloverHDMI-xxx.command/gDebug=1
```

Yesterday I update 10.12.4. Afterwards i ran `audio_cloverHDMI-120_v1.0d.command` once again. Restart machine.
My hackintosh is still process.
So i reinstall  hackintosh.
Now I have come to this step.
I remember my hackintosh 10.12.2 run `audio_cloverHDMI-120_v1.0d.command` is Ok.
Thanks for your help
