### ISSUE TITLE
Question:10.12.4

### ISSUE THREAD

**Issue by RoJoHub** [toleda/audio_CloverHDMI#13]
@toleda.
I have another question.
How to Set audio_cloverHDMI-xxx.command/gDebug=1
```
Test Drive
- Set audio_cloverHDMI-xxx.command/gDebug=1
```
The day before yesterday I update 10.12.4. Afterwards i ran `audio_cloverHDMI-120_v1.0d.command` once again. 
My hackintosh is still process after restart machine.
So i reinstall hackintosh.
Now I have come to this step.
I remember my hackintosh 10.12.2 run `audio_cloverHDMI-120_v1.0d.command` is Ok.
Thanks for your help

**Comment by RoJoHub** [comment]
There is an option in the menu in MultiBeast.
![wx20170428-090113](https://cloud.githubusercontent.com/assets/15648309/25510248/44699098-2bf1-11e7-8a42-f17f54f4bd9b.png)
```
 - I.cloverHDMI (script)
    - detects and installs appropriate ssdt(s)
```
So i think I finished this step.
After all of run.
`Using Intel HD530 with Dual Monitors`is not working
But hdmi is effective.

**Comment by toleda** [comment]
For debug=1
1. open the script with Xcode or a text editor
2. find gDebug=0
3. set gDebug=1
4. save

For any install, run cloverHDMI once. Software Update has no effect on ACPI edits.

The HD3000/HD4000 selection sets Audio ID = 3, does not enable HDMI audio.  Does not apply to HD530, description error.

See README/Problem Reporting, attach requested files.
