### ISSUE TITLE
High Sierra Support

### ISSUE THREAD

**Issue by mugukamil** [toleda/audio_CloverHDMI#18]
<img width="734" alt="screen shot 2017-10-09 at 15 01 29" src="https://user-images.githubusercontent.com/4193470/31337180-c76b3d74-ad02-11e7-9566-be92bb5a814a.png">

**Comment by toleda** [comment]
Missed https://github.com/toleda/audio_CloverHDMI/blob/master/audio_cloverHDMI-130.command.zip

**Comment by mugukamil** [comment]
@toleda thanks, didn't see it in readme.
