### ISSUE TITLE
How to do a clean uninstall of the script? Only aml file?

### ISSUE THREAD

**Issue by iaomw** [toleda/audio_CloverHDMI#22]

**Comment by toleda** [comment]
As appropriate:
1. Intel, remove:
EFI/CLOVER/ACPI/patched/SSDT-HDMI-HD....aml
EFI/CLOVER/KernelAndKextPatches/KextsToPatch/AppleIntelxxxGraphics...kext
2. AMD, remove:
EFI/CLOVER/ACPI/patched/SSDT-HDMI-AMD-....-.aml
EFI/CLOVER/KernelAndKextPatches/KextsToPatch/AMDxxxxController.kext
3. Nvidia, remove:
EFI/CLOVER/ACPI/patched/SSDT-HDMI-NVIDIA-....-.aml

**Comment by iaomw** [comment]
Thanks.
